export default {
  UPDATE_BNB_PRICE: 'UPDATE_BNB_PRICE',
  UPDATE_FARMS: 'UPDATE_FARMS',
  UPDATE_ASSETS: 'UPDATE_ASSETS',
  APPEND_ASSET: 'APPEND_ASSET',
  APPEND_FARM: 'APPEND_FARM',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  RESET_ASSET_AND_FARM: 'RESET_ASSET_AND_FARM',
  UPDATE_CURRENCY: 'UPDATE_CURRENCY',
  UPDATE_RATES: 'UPDATE_RATES',
}
