export default {
  LOGO: '/images/logo.png',
  LOGO_DARK: '/images/logo-dark.png',
  METAMASK: '/images/metamask.svg',
  IMTOKEN: '/images/imToken.png',
  BDO: '/images/protocols/bdo.png',
  AUTOFARM: '/images/protocols/autofarm.png',
  BEEFY: '/images/protocols/beefy.png',
  ACRYPTOS: '/images/protocols/cream.png',
  VENUS: '/images/protocols/venus.png',
  PANCAKE: '/images/protocols/pancake.png',
  CREAM: '/images/protocols/cream.png',
  ALPACA: '/images/protocols/alpaca.svg',
  MIDAS: '/images/protocols/midas.png',
  BELT: '/images/protocols/belt.png',
  ELLIPSIS: '/images/protocols/ellipsis.png',
  WAULT: '/images/protocols/wault.png',
  POPSICLE: '/images/protocols/popsicle.jpg',
  URANIUM: '/images/protocols/uranium.jpg',
}
